#! /bin/zsh

local source="${(%):-%x}"
local pwd="$(cd "$( dirname "$source" )" && pwd)"

read "USER?user: "

read "EMAIL?email: "

# setup ssh
if ! [ -f ~/.ssh/id_rsa ]; then
  read "yn?Do you want to create ssh key? (yes/no) "

  case $yn in
    yes ) ssh-keygen -t rsa -b 4096 -C "$EMAIL";;
    no ) echo "exiting...";
      exit;;
    * ) echo "invalid response";
      exit 1;;
  esac
fi

# install xcode command line tools
sudo xcode-select --install

# install rosetta2
sudo softwareupdate --install-rosetta

# install oh-my-zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sed 's/exec zsh -l//g')"

# install homebrew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
eval "$(/opt/homebrew/bin/brew shellenv)"

brew update
brew install --cask docker docker-compose flux slack wechat whatsapp dropbox google-chrome sublime-text authy rectangle zoom drawio chatbox
# brew install --cask visual-studio-code intellij-idea goland pycharm datagrip
brew install telnet ack jq tree watch wget colordiff fzf ripgrep asdf libxslt gnupg wxwidgets fop pure socat bison automake \
     libtool openssl wxmac flex thrift kubectl helm clusterctl kind clusterawsadm \
     ollama
brew upgrade

# install fzf
$(brew --prefix)/opt/fzf/install --all

# install powerlevel10k theme
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/powerlevel10k
git clone --depth=1 https://github.com/powerline/fonts.git ~/powerlevel10k/fonts
~/powerlevel10k/fonts/install.sh

# install & configure fly vim, iTerm2, tmux
rm -rf ~/maximum-awesome && git clone https://github.com/square/maximum-awesome.git ~/maximum-awesome && cd ~/maximum-awesome/ && rake
cd -

line="source $pwd/vim/.vimrc.bundles.local"
grep -qF -- "$line" ~/.vimrc.bundles.local 2>/dev/null || echo "$line" >> ~/.vimrc.bundles.local

line="source $pwd/vim/.vimrc.local"
grep -qF -- "$line" ~/.vimrc.local 2>/dev/null || echo "$line" >> ~/.vimrc.local

vim +PluginInstall +qall
vim +GoInstallBinaries +qall

cd ~/.vim/bundle/coc.nvim
npm ci
npm run build
cd -


# install iTerm2 color
(curl -Ls https://raw.githubusercontent.com/sindresorhus/iterm2-snazzy/main/Snazzy.itermcolors > /tmp/Snazzy.itermcolors && open /tmp/Snazzy.itermcolors)

# configure tmux
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
line="source $pwd/tmux/.tmux.conf.local"
grep -qF -- "$line" ~/.tmux.conf.local 2>/dev/null || echo "$line" >> ~/.tmux.conf.local

# configure git
git config --global alias.co checkout
git config --global alias.br branch
git config --global alias.cp cherry-pick
git config --global alias.cm commit
git config --global alias.df diff
git config --global alias.st status
git config --global user.name "$USER"
git config --global user.email "$EMAIL"

# install asdf plugins
asdf plugin-add golang
asdf plugin-add java
asdf plugin-add erlang
asdf plugin-add elixir
asdf plugin-add ruby
asdf plugin-add python
asdf plugin-add rebar
asdf plugin-add nodejs
asdf plugin-add rust

# install defaults
asdf install nodejs 23.4.0
asdf global nodejs 23.4.0
npm config set prefix ~/.npm-global

asdf install golang 1.23.4
asdf global golang 1.23.4

asdf install java openjdk-23.0.1
asdf global java openjdk-23.0.1

# install vagrant plugins
# vagrant plugin install landrush
# vagrant plugin install vagrant-hosts

# enable gobin
cat $pwd/golang/set-env.zsh > ~/.asdf/plugins/golang/set-env.zsh

line="source $pwd/zsh/.zprofile"
grep -qF -- "$line" ~/.zprofile 2>/dev/null || echo "$line" >> ~/.zprofile

line="source $pwd/zsh/.zshrc"
grep -qF -- "$line" ~/.zshrc 2>/dev/null || echo "$line" >> ~/.zshrc

source ~/.zprofile
source ~/.zshrc
