packloadall
let mapleader = ","

syntax on
set nowrap
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab
set autoindent
set number
set showcmd
set cursorline
filetype plugin indent on
set wildmenu
set lazyredraw
set showmatch
set incsearch
set hlsearch
set foldenable
set foldlevelstart=10
set foldnestmax=10
set foldmethod=indent

set background=dark
let g:lightline = { 'colorscheme': 'palenight' }
let g:palenight_terminal_italics = 1
let g:rehash256 = 1
let g:molokai_original = 1
colorscheme molokai

let g:NERDTreeNodeDelimiter = "\u00a0"
let g:NERDTreeWinPos = "right"
let NERDTreeShowHidden = 1
let g:ctrlp_user_command = ['.git/', 'git --git-dir=%s/.git ls-files -oc --exclude-standard']

nnoremap <SPACE> za
nnoremap <leader><SPACE> :nohlsearch<CR>
nnoremap <leader>ev :vsplit $MYVIMRC<CR>
nnoremap <leader>sv :source $MYVIMRC<CR>
vnoremap // y/<C-R>"<CR>
map <leader>o :BufExplorer<CR>
map <leader>f :MRU<CR>
map <leader>z :Goyo<CR>

autocmd BufWritePre * %s/\s\+$//e

augroup vagrant
  au!
  au BufRead,BufNewFile Vagrantfile set filetype=ruby
augroup END

augroup kubeconfig
  au!
  autocmd BufNewFile,BufRead *.kubeconfig set syntax=yaml
augroup END

augroup systemd
  au!
  autocmd BufNewFile,BufRead *.service set syntax=systemd
augroup END

augroup env
  au!
  autocmd BufNewFile,BufRead *.env set syntax=sh
augroup END

nnoremap =j :%!python -m json.tool<CR>
nnoremap <leader>F :CtrlSF<SPACE>
nnoremap tt :NERDTreeToggle<CR>
nnoremap tf :NERDTreeFind<CR>
inoremap {<CR> {<CR>}<ESC>ko

nnoremap <C-j> :m .+1<CR>==
nnoremap <C-k> :m .-2<CR>==
inoremap <C-j> <ESC>:m .+1<CR>==gi
inoremap <C-k> <ESC>:m .-2<CR>==gi
vnoremap <C-j> :m '>+1<CR>gv=gv
vnoremap <C-k> :m '<-2<CR>gv=gv
vnoremap aa <ESC>gg0vG$
nnoremap <leader>G :GoImports<CR>
nnoremap <leader>g :GoImport<SPACE>
nnoremap == ggVG=
