packloadall
let mapleader = ","

syntax on
set nowrap
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab
set autoindent
set number
set showcmd
set cursorline
filetype plugin indent on
set wildmenu
set lazyredraw
set showmatch
set incsearch
set hlsearch
set foldenable
set foldlevelstart=10
set foldnestmax=10
set foldmethod=indent

set background=dark
let g:lightline = { 'colorscheme': 'palenight' }
let g:palenight_terminal_italics = 1
let g:rehash256 = 1
let g:molokai_original = 1
colorscheme molokai

let g:NERDTreeNodeDelimiter = "\u00a0"
let g:NERDTreeWinPos = "right"
let NERDTreeShowHidden = 1

nnoremap <space> za
nnoremap <leader><space> :nohlsearch<CR>
nnoremap <leader>ev :vsplit $MYVIMRC<cr>
nnoremap <leader>sv :source $MYVIMRC<cr>
vnoremap // y/<C-R>"<CR>
map <leader>o :BufExplorer<cr>
map <leader>f :MRU<CR>
map <leader>z :Goyo<cr>

autocmd BufWritePre * %s/\s\+$//e

augroup vagrant
  au!
  au BufRead,BufNewFile Vagrantfile set filetype=ruby
augroup END
