export PS1='\[\e[00m\]\u\[\e[00;33m\]@\h\[\e[00m\]\[\e[00;31m\]\[\e[00m\]:\[\e[01;36m\]\w\[\e[00m\]\$ '
export EDITOR='vim'
alias ll='ls -lha'

# git bash prompt
export GIT_PROMPT_ONLY_IN_REPO=1
export GIT_PROMPT_THEME=Single_line_Ubuntu_Minimalist
source ~/.bash-git-prompt/gitprompt.sh

# use vi editing mode in bash
set -o vi
